In [1]:
import pandas as pd

In [15]:
coins = pd.read_csv("coin_Bitcoin.csv")

In [16]:
coins

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...,...
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [21]:
coins.drop(columns=["SNo"], inplace=True)

In [22]:
coins.drop(0)

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
1,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
5,Bitcoin,BTC,2013-05-04 23:59:59,115.000000,92.500000,98.099998,112.500000,0.000000e+00,1.250317e+09
...,...,...,...,...,...,...,...,...,...
2986,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [23]:
coins.drop(coins.index[0:6])

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
6,Bitcoin,BTC,2013-05-05 23:59:59,118.800003,107.142998,112.900002,115.910004,0.000000e+00,1.288693e+09
7,Bitcoin,BTC,2013-05-06 23:59:59,124.663002,106.639999,115.980003,112.300003,0.000000e+00,1.249023e+09
8,Bitcoin,BTC,2013-05-07 23:59:59,113.444000,97.699997,112.250000,111.500000,0.000000e+00,1.240594e+09
9,Bitcoin,BTC,2013-05-08 23:59:59,115.779999,109.599998,109.599998,113.566002,0.000000e+00,1.264049e+09
10,Bitcoin,BTC,2013-05-09 23:59:59,113.459999,109.260002,113.199997,112.669998,0.000000e+00,1.254535e+09
...,...,...,...,...,...,...,...,...,...
2986,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [41]:
coins["crypto"]=coins["Name"]+coins["Symbol"]

In [39]:
coins.drop(columns=["Crypto","crypto","cypto"], inplace = True)

In [40]:
coins

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...
2986,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [42]:
coins.insert(0,"Cryptotype",coins["crypto"])

In [43]:
coins

,Cryptotype,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,crypto
0,BitcoinBTC,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09,BitcoinBTC
1,BitcoinBTC,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09,BitcoinBTC
2,BitcoinBTC,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09,BitcoinBTC
3,BitcoinBTC,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09,BitcoinBTC
4,BitcoinBTC,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09,BitcoinBTC
...,...,...,...,...,...,...,...,...,...,...,...
2986,BitcoinBTC,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11,BitcoinBTC
2987,BitcoinBTC,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11,BitcoinBTC
2988,BitcoinBTC,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11,BitcoinBTC
2989,BitcoinBTC,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11,BitcoinBTC
2990,BitcoinBTC,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11,BitcoinBTC

In [48]:
coins.drop(columns=["crypto"],inplace=True)

In [49]:
coins

,Cryptotype,Date,High,Low,Open,Close,Volume,Marketcap
0,BitcoinBTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,BitcoinBTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,BitcoinBTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,BitcoinBTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,BitcoinBTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...
2986,BitcoinBTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,BitcoinBTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,BitcoinBTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,BitcoinBTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,BitcoinBTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [54]:
coins["Average"] = coins["High"] + coins["Low"]

In [55]:
coins

,Cryptotype,Date,High,Low,Open,Close,Volume,Marketcap,Average
0,BitcoinBTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09,281.488007
1,BitcoinBTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09,280.979996
2,BitcoinBTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09,247.610001
3,BitcoinBTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09,217.881897
4,BitcoinBTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09,187.227997
...,...,...,...,...,...,...,...,...,...
2986,BitcoinBTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11,66710.269480
2987,BitcoinBTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11,68311.956435
2988,BitcoinBTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11,70334.044605
2989,BitcoinBTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11,68498.005464
2990,BitcoinBTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11,68638.452533

In [62]:
coins.sort_values("Average", ascending=False).head(10)

,Cryptotype,Date,High,Low,Open,Close,Volume,Marketcap,Average
2907,BitcoinBTC,2021-04-14 23:59:59,64863.098908,61554.796690,63523.754869,63109.695935,7.745178e+10,1.179061e+12,126417.895598
2908,BitcoinBTC,2021-04-15 23:59:59,63821.672193,62208.964366,63075.196221,63314.010845,6.095438e+10,1.182945e+12,126030.636558
2909,BitcoinBTC,2021-04-16 23:59:59,63594.720913,60222.532079,63258.505174,61572.789601,8.429301e+10,1.150457e+12,123817.252992
2906,BitcoinBTC,2021-04-13 23:59:59,63742.283337,59869.956293,59890.017790,63503.457930,6.998345e+10,1.186364e+12,123612.239630
2910,BitcoinBTC,2021-04-17 23:59:59,62572.176051,60361.352179,61529.920997,60683.821233,6.613876e+10,1.133882e+12,122933.528230
2876,BitcoinBTC,2021-03-14 23:59:59,61597.918396,59302.316977,61221.134297,59302.316977,4.390123e+10,1.106226e+12,120900.235373
2905,BitcoinBTC,2021-04-12 23:59:59,61253.036916,59589.873756,60175.944757,59893.451889,5.182869e+10,1.118871e+12,120842.910672
2904,BitcoinBTC,2021-04-11 23:59:59,60790.555315,59289.795631,59846.230786,60204.964914,4.628025e+10,1.124636e+12,120080.350946
2903,BitcoinBTC,2021-04-10 23:59:59,61276.665366,58038.706278,58253.776809,59793.235410,5.823847e+10,1.116890e+12,119315.371644
2895,BitcoinBTC,2021-04-02 23:59:59,60267.187650,58869.279968,59098.879070,59384.313359,5.872786e+10,1.108814e+12,119136.467618